#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : crashtest
Version  : 0.3.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/08/3c/5ec13020a4693fab34e1f438fe6e96aed6551740e1f4a5cc66e8b84491ea/crashtest-0.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/08/3c/5ec13020a4693fab34e1f438fe6e96aed6551740e1f4a5cc66e8b84491ea/crashtest-0.3.1.tar.gz
Summary  : Manage Python errors with ease
Group    : Development/Tools
License  : MIT
Requires: crashtest-python = %{version}-%{release}
Requires: crashtest-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
# Crashtest
Crashtest is a Python library that makes exceptions handling and inspection easier.

%package python
Summary: python components for the crashtest package.
Group: Default
Requires: crashtest-python3 = %{version}-%{release}

%description python
python components for the crashtest package.


%package python3
Summary: python3 components for the crashtest package.
Group: Default
Requires: python3-core
Provides: pypi(crashtest)

%description python3
python3 components for the crashtest package.


%prep
%setup -q -n crashtest-0.3.1
cd %{_builddir}/crashtest-0.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637363075
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
